apiVersion: apps/v1
kind: StateFulSet
metadata:
  name: dbapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: cont-1
          image: chandu455/vam:dbimage-v1
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: vam


---
apiVersion: v1
kind: Service
metadata:
  name: devopsdb
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
